### ISSUE TITLE
Override sorting type when using t.crud

### ISSUE THREAD

**Issue by bmaciass** [morgothulhu/nexus-plugin-prisma#28]
Hi, first of all, thank you for maintaining this fork even when the original is deprecated.

This is not an issue rather a question, I'm upgrading prisma from 3.x to 5.1.0 and using t.crud is generating new types instead of the old ones which is a breaking change in our graphql schema.

If a model `MyModel` have a nullable field `x`, then if I do `t.crud.mymodel({ ordering : { x: true } })` 

then, the generated input in my schema.graphql is `input QueryMyModelOrderByInput { x: SortOrderInput }`

previously, the generated type in prisma@3.x using an older version of nexus-plugin-prisma will generate `input QueryModelOrderByInput { x: SortOrderInput }` which I know is fine since `SortOrderInput` is an improvement but, in my case, for my current existing graphql schema is a breaking change since it will affect the frontend (cached versions especifically).

Given this context, my question is: do you know how can I keep backwards compatibility by using like `SortOrderInput | SortOrder` when using this library? The workaround I realized is by manually overwriting the generated schema and/or creating another query like a v2.

Thanks in advance.

**Comment by morgothulhu** [comment]
@bmaciass thx for the issue. Could you provide the full type info for `SortOrderInput` and `SortOrder` (respectively latest prisma vs. prisma@3.x)? (or a small repro so I can look).

Looking at this repo (between commits 25329130357f106b13f4514d72e54c34d334db36 and 25329130357f106b13f4514d72e54c34d334db36), I see the `./tests/__app/generated/schema.graphql` generated file creating `SortOrder` in both cases, as:

```
enum SortOrder {
  asc
  desc
}
```

**Comment by bmaciass** [comment]
@morgothulhu sorry for the very late response, I _think_ when upgrading to prisma v5 the Sort enums changed when the field being ordered accepts null. If a field does not accept null the sort enum remains the same.

In short, upgrading from prisma v3 to v5 and generating schema.graphql by running nexus breaks the schema; so I fixed this by manually creating the SortOrder enum - in this way, the enum won't be created at all and the schema won't break :sweat_smile:
